### ISSUE TITLE
navigation bar

### ISSUE THREAD

**Issue by livinhigh** [UNIFORMatom/iwpproject#3]
edda, your navigation bar in home page, support page and community page are different. Make them same

**Comment by UNIFORMatom** [comment]
y should home page have the link to home page itself?
each page doesnt gave the link to itself.. thats a feature

**Comment by livinhigh** [comment]
dude, its design sense honestly, just because its on that page, doesnt mean the link shouldnt be there, oru fixed nav bar anengil users wont get confused. If you check, most websites do that.
